'use strict';
const {CHARACTER_SCALE}=require('../character-config.js');
process.env.WORLD_MAP='mill';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{createRequire}=require('node:module'),{EventEmitter}=require('node:events');
const root=path.join(__dirname,'..'),req=createRequire(path.join(root,'server.cjs'));
const fakeServer={on(){return this},listen(){return this}};
const ctx={require:n=>n==='http'?{createServer:()=>fakeServer}:n==='ws'?{WebSocketServer:class extends EventEmitter{},WebSocket:{OPEN:1}}:req(n),console,process:{env:{},exit(){throw Error('Unexpected exit')}},__dirname:root,setInterval(){},Date,Math};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'server.cjs'),'utf8')+'\nglobalThis.e={WEAPONS,SKINS,players,clients,spawn,shoot,startRound,cleanGrenades,throwGrenade,refreshEquipment,detonate,changeLoadout,playerHit,playerEye,publicPlayer,getGrenades:()=>grenades};',ctx);const e=ctx.e;
function p(id,x=3,z=20){return {id,name:id,skin:'cyan',x,y:0,z,yaw:0,pitch:0,vy:0,ground:true,hp:100,shield:0,input:{aim:true},loadout:['rifle','pistol'],grenadeLoadout:['frag','medkit'],guns:['rifle','pistol'],slot:0,ammo:[30,12],reloadAt:0,nextShot:0,kills:0,deaths:0,damage:0,grenades:[true,true],streak:0,flashUntil:0};}
function reset(){e.players.clear();e.clients.clear();}
function add(p){const messages=[];e.players.set(p.id,p);e.clients.set(p.id,{readyState:1,send:s=>messages.push(JSON.parse(s))});return messages;}
let count=0;function test(name,fn){fn();count++;console.log('PASS',name);}
test('Ten distinct weapons and twelve cosmetic skin choices are validated',()=>{assert.equal(Object.keys(e.WEAPONS).length,10);assert.equal(Object.keys(e.SKINS).length,12);assert.deepEqual(Array.from(e.cleanGrenades(['frag','medkit'])),['frag','medkit']);assert.deepEqual(Array.from(e.cleanGrenades(['invalid','smoke'])),['flash','smoke']);});
test('Every weapon fires through the authoritative shooting path and consumes one round',()=>{for(const id of Object.keys(e.WEAPONS)){reset();const a=p('a'),b=p('b',3,14),m=add(a);add(b);a.guns=[id,'pistol'];a.ammo=[e.WEAPONS[id].magazine,12];e.shoot(a,10000);assert.equal(a.ammo[0],e.WEAPONS[id].magazine-1,id);assert.ok(m.some(m=>m.kind==='shot'&&m.gun===id));assert.ok(b.hp<100,id);}});
test('Medkits heal at most 45, never overheal, and full-health use does not consume a slot',()=>{reset();const a=p('a');add(a);e.throwGrenade(a,1,10000);assert.ok(a.grenades[1]);a.hp=80;e.throwGrenade(a,1,10001);assert.equal(a.hp,100);assert.equal(a.gearReadyAt[1],25001);assert.ok(!a.grenades[1]);a.hp=10;e.throwGrenade(a,1,10002);assert.equal(a.hp,10);e.throwGrenade(a,1,25001);assert.equal(a.hp,55);});
test('Equipment refills at 15 seconds, preserves weapon ammo and keeps cooldown through death',()=>{const a=p('a');e.throwGrenade(a,0,10000);a.ammo[0]=7;e.refreshEquipment(a,24999);assert.ok(!a.grenades[0]);e.spawn(a,20000);assert.ok(!a.grenades[0]);a.ammo[0]=7;e.refreshEquipment(a,25000);assert.ok(a.grenades[0]);assert.equal(a.ammo[0],7);});
test('Frag damage falls off with distance and solid cover blocks blast damage',()=>{reset();const a=p('a'),near=p('near',3,18),far=p('far',3,12),covered=p('covered',30,24);add(a);add(near);add(far);add(covered);e.detonate({kind:'frag',owner:'a',x:3,y:.8,z:20},10000);assert.ok(near.hp<far.hp);assert.ok(a.hp<100);e.detonate({kind:'frag',owner:'a',x:33,y:1,z:24},10000);assert.equal(covered.hp,100);});
test('Frag kills credit the owner, respect spawn shields and do not award self-kills',()=>{reset();const a=p('a',3,25),b=p('b',3,20),c=p('c',3,20);c.shield=20000;add(a);add(b);add(c);e.detonate({kind:'frag',owner:'a',x:3,y:.86*CHARACTER_SCALE,z:20},10000);assert.equal(b.hp,0);assert.equal(c.hp,100);assert.equal(a.kills,1);a.hp=1;e.detonate({kind:'frag',owner:'a',x:3,y:.86*CHARACTER_SCALE,z:25},10000);assert.equal(a.hp,0);assert.equal(a.kills,1);});
test('Stance-aware hitboxes allow bullets above a crouched or prone operator to pass',()=>{const a=p('a',0,0),o={x:0,y:1.5*CHARACTER_SCALE,z:-5},d={x:0,y:0,z:1};assert.ok(e.playerHit(a,o,d).head<150);a.stance='crouch';assert.equal(e.playerHit(a,o,d).body,Infinity);assert.equal(e.playerHit(a,o,d).head,Infinity);a.stance='prone';assert.ok(e.playerEye(a).y<.4);const head=e.playerHit(a,{x:0,y:.4*CHARACTER_SCALE,z:-5},d);assert.ok(head.head<150);});
test('Round start refills equipment and locks loadout changes, including pending-respawn changes',()=>{reset();const a=p('a');add(a);a.gearReadyAt=[Date.now()+15000,Date.now()+15000];e.startRound();assert.ok(a.grenades.every(Boolean));const original=[...a.loadout];assert.equal(e.changeLoadout(a,{loadout:['sniper','lmg'],grenades:['smoke','flash'],skin:'ember'},Date.now()),false);e.spawn(a,Date.now()+6000);assert.deepEqual([...a.guns],original);assert.equal(a.skin,'cyan');assert.deepEqual([...a.grenadeLoadout],['frag','medkit']);});
const {MapCollision,bodyShape}=require('../map-collision.cjs');const tris=[];function quad(a,b,c,d){tris.push(...a,...b,...c,...a,...c,...d)}quad([-20,0,-20],[-20,0,20],[20,0,20],[20,0,-20]);quad([-2,1.28*CHARACTER_SCALE,-5],[-2,1.28*CHARACTER_SCALE,0],[2,1.28*CHARACTER_SCALE,0],[2,1.28*CHARACTER_SCALE,-5]);const collision=new MapCollision(new Float32Array(tris));
function step(a,n){for(let i=0;i<n;i++)collision.move(a,1/60);}
test('Crouch can enter low cover and releasing crouch cannot stand into the ceiling',()=>{const a=p('a',0,1);a.input={forward:true,crouch:true};step(a,45);assert.equal(a.stance,'crouch');assert.ok(a.z<0);a.input={};step(a,20);assert.equal(a.stance,'crouch');assert.ok(!collision.blocked(a.x,a.y,a.z,.36,bodyShape(a).height));});
test('Prone uses a lower, wider collision volume and moves more slowly',()=>{const a=p('a',6,5);a.input={prone:true,forward:true};step(a,60);assert.equal(a.stance,'prone');assert.ok(a.z>3&&a.z<5);assert.equal(bodyShape(a).height,.52*CHARACTER_SCALE);a.input={};step(a,2);assert.equal(a.stance,'stand');});
test('Sprint-to-slide boosts momentum then expires, with no immediate repeated boost',()=>{const a=p('a',6,10);a.input={forward:true,sprint:true};step(a,40);a.input.slide=true;step(a,1);assert.equal(a.stance,'slide');assert.ok(Math.hypot(a.vx,a.vz)>10);step(a,55);assert.equal(a.stance,'stand');a.input.slide=false;step(a,1);a.input.slide=true;step(a,1);assert.notEqual(a.stance,'slide');});
test('Jump is buffered, follows a smooth arc and does not repeatedly trigger while held',()=>{const a=p('a',6,5);a.input={jump:true};let takeoffs=0,max=0,last=true;for(let i=0;i<180;i++){collision.move(a,1/60);if(last&&!a.ground)takeoffs++;last=a.ground;max=Math.max(max,a.y);}assert.equal(takeoffs,1);assert.ok(max>1&&max<1.6);assert.ok(a.ground);});
console.log(`${count} combat upgrade checks passed.`);
