'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),{MapCollision,bodyShape}=require('../map-collision.cjs'),world=require('../public/maps/village-world.json'),{audit}=require('../scripts/map-navigation.cjs');
const raw=fs.readFileSync('public/maps/village-collision.bin'),c=new MapCollision(new Float32Array(raw.buffer,raw.byteOffset,raw.byteLength/4));let count=0;
function test(name,fn){fn();count++;console.log('PASS',name);}
function player(x,z,y=0,yaw=0){return {x,y,z,yaw,vy:0,ground:true,input:{},stance:'stand'};}
function step(p,n){for(let i=0;i<n;i++)c.move(p,1/60);}
test('Bellhaven retains Subzero and has approximately twice its map footprint',()=>{const catalog=require('../map-catalog.cjs');assert.equal(catalog.worlds.subzero.MAP.id,'subzero');assert.equal(catalog.worlds.village.MAP.id,'village');const b=world.MAP.bounds,s=catalog.worlds.subzero.MAP.bounds;const ratio=(b.maxX-b.minX)*(b.maxZ-b.minZ)/((s.maxX-s.minX)*(s.maxZ-s.minZ));assert.ok(ratio>=1.9&&ratio<=2.1);});
test('All sixteen spawn volumes are clear and remain supported',()=>{assert.equal(world.SPAWNS.length,16);for(const [x,z,y]of world.SPAWNS){const p=player(x,z,y);assert.ok(!c.blocked(x,y,z));step(p,90);assert.ok(Math.abs(p.y-y)<.04);assert.ok(p.ground);}});
test('Closed buildings stop players, bullets and thrown equipment',()=>{const p=player(-34,16,0,-Math.PI/2);p.input={forward:true,sprint:true};step(p,100);assert.ok(p.x<-29.5);assert.ok(c.distance({x:-34,y:1,z:16},{x:1,y:0,z:0},20)<5);assert.ok(c.projectile(-29.3,.6,16,.12));});
test('The central arch is passable and its pillars block movement',()=>{const p=player(-1,4,0,0);p.input={forward:true};step(p,90);assert.ok(p.z<-3);assert.ok(!c.blocked(p.x,p.y,p.z));const pillar=player(0,4);pillar.input={forward:true};step(pillar,90);assert.ok(pillar.z>1.5);});
test('Both stairs reach their three-meter platforms and end rails prevent walking off',()=>{for(const [x,z,yaw]of [[-9,-3,0],[9,3,Math.PI]]){const p=player(x,z,0,yaw);p.input={forward:true};let max=0;for(let i=0;i<160;i++){c.move(p,1/60);max=Math.max(max,p.y);}assert.ok(max>2.95,'stair height '+max);assert.ok(p.y>2.9,'stays on upper platform');assert.ok(!c.blocked(p.x,p.y,p.z));}});
test('The two ground-floor interiors have usable entrances and solid ceilings',()=>{for(const [x,z]of [[-20,-16],[20,16]]){const p=player(x,z+14);p.input={forward:true};step(p,70);assert.ok(p.z<z+10,'entered room');p.input={jump:true};let max=0;for(let i=0;i<100;i++){c.move(p,1/60);max=Math.max(max,p.y);}assert.ok(max+bodyShape(p).height<3.1);}});
test('All spawn approaches connect through the actual collision network',()=>{const result=audit(world,'public/maps/village-collision.bin');assert.ok(result.spawnsConnected.every(Boolean));assert.ok(result.cells>2000);});
test('Compiled map and collision gzip files match and map credits are retained',()=>{const zlib=require('node:zlib');for(const name of ['village.glb','village-collision.bin'])assert.deepEqual(zlib.gunzipSync(fs.readFileSync('public/maps/'+name+'.gz')),fs.readFileSync('public/maps/'+name));assert.match(fs.readFileSync('public/maps/village-license.txt','utf8'),/CC0/);const b=fs.readFileSync('public/maps/village.glb');assert.equal(b.readUInt32LE(0),0x46546c67);assert.equal(b.readUInt32LE(8),b.length);});
console.log(count+' Bellhaven checks passed.');
