'use strict';
// Offline GLB compiler: bake node transforms, weld equal vertices, partition by
// material and location, and derive collision from the same transformed triangles.
const fs=require('node:fs'),path=require('node:path'),THREE=require('three');
const root=path.join(__dirname,'..'),dir=path.join(root,'public/maps');
const source=fs.readFileSync(process.argv[2]||path.join(dir,'subzero-source.glb'));
if(source.readUInt32LE(0)!==0x46546c67)throw Error('Expected GLB');
const jsonLength=source.readUInt32LE(12),g=JSON.parse(source.subarray(20,20+jsonLength));
const bin=source.subarray(28+jsonLength),scale=.1,offset=[-70,-53,230];
function accessor(id){const a=g.accessors[id],v=g.bufferViews[a.bufferView],size={SCALAR:1,VEC2:2,VEC3:3,VEC4:4}[a.type],bytes={5121:1,5123:2,5125:4,5126:4}[a.componentType],read={5121:'readUInt8',5123:'readUInt16LE',5125:'readUInt32LE',5126:'readFloatLE'}[a.componentType];if(!read||a.sparse)throw Error('Unsupported accessor');return Array.from({length:a.count},(_,i)=>Array.from({length:size},(_,k)=>{let n=bin[read]((v.byteOffset||0)+(a.byteOffset||0)+i*(v.byteStride||size*bytes)+k*bytes);return a.normalized?n/({5121:255,5123:65535}[a.componentType]||1):n;}));}
const buckets=new Map(),collision=[],preview=[];let inputTriangles=0,removed=0;
function visit(id,parent){const n=g.nodes[id],local=n.matrix?new THREE.Matrix4().fromArray(n.matrix):new THREE.Matrix4().compose(new THREE.Vector3(...(n.translation||[0,0,0])),new THREE.Quaternion(...(n.rotation||[0,0,0,1])),new THREE.Vector3(...(n.scale||[1,1,1]))),matrix=parent.clone().multiply(local),normalMatrix=new THREE.Matrix3().getNormalMatrix(matrix);
if(n.mesh!==undefined)for(const p of g.meshes[n.mesh].primitives){if(p.mode!==undefined&&p.mode!==4)throw Error('Triangles only');const pos=accessor(p.attributes.POSITION).map(v=>new THREE.Vector3(...v).applyMatrix4(matrix).add(new THREE.Vector3(...offset)).multiplyScalar(scale).toArray()),norm=accessor(p.attributes.NORMAL).map(v=>new THREE.Vector3(...v).applyNormalMatrix(normalMatrix).toArray()),uv=p.attributes.TEXCOORD_0===undefined?pos.map(()=>[0,0]):accessor(p.attributes.TEXCOORD_0),color=p.attributes.COLOR_0===undefined?pos.map(()=>[1,1,1,1]):accessor(p.attributes.COLOR_0).map(c=>c.length===3?[...c,1]:c),indices=p.indices===undefined?pos.map((_,i)=>i):accessor(p.indices).flat();
for(let i=0;i<indices.length;i+=3){inputTriangles++;const ids=indices.slice(i,i+3),points=ids.map(j=>pos[j]);if(points.every(v=>v[0]<-85)||points.every(v=>v[0]>55)||points.every(v=>v[2]<-50)||points.every(v=>v[2]>55)){removed++;continue;}const center=points.reduce((s,v)=>s.add(new THREE.Vector3(...v)),new THREE.Vector3()).multiplyScalar(1/3),key=p.material+':'+Math.floor(center.x/16)+':'+Math.floor(center.z/16);if(!buckets.has(key))buckets.set(key,{material:p.material,vertices:[],indices:[],seen:new Map()});const b=buckets.get(key);for(const j of ids){const v=[...pos[j],...norm[j],...uv[j],...color[j]],k=v.map(x=>Math.round(x*1e6)).join(',');if(!b.seen.has(k)){b.seen.set(k,b.vertices.length);b.vertices.push(v);}b.indices.push(b.seen.get(k));}
const tri=points.flat();if(g.materials[p.material].alphaMode!=='BLEND'){const t=new THREE.Triangle(...points.map(v=>new THREE.Vector3(...v)));if(t.getArea()>1e-8){collision.push(...tri);if(t.getNormal(new THREE.Vector3()).y>.6)preview.push({points,material:p.material});}}
}}
for(const child of n.children||[])visit(child,matrix);}
for(const id of g.scenes[g.scene||0].nodes)visit(id,new THREE.Matrix4());
const out={asset:{version:'2.0',generator:'Neon Yard offline map compiler',extras:g.asset.extras},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],materials:g.materials,textures:g.textures,samplers:g.samplers,images:[],accessors:[],bufferViews:[],buffers:[],extensionsUsed:['KHR_materials_unlit']};
for(const m of out.materials)m.extensions={...m.extensions,KHR_materials_unlit:{}};
const chunks=[];let length=0;function view(data){const padded=Buffer.alloc(Math.ceil(data.length/4)*4);data.copy(padded);const id=out.bufferViews.length;out.bufferViews.push({buffer:0,byteOffset:length,byteLength:data.length});chunks.push(padded);length+=padded.length;return id;}
function attr(values,size,type='VEC3',integer=false){const a=integer?new Uint16Array(values):type==='VEC4'?new Uint8Array(values.map(v=>Math.round(Math.max(0,Math.min(1,v))*255))):new Float32Array(values),id=out.accessors.length;const item={bufferView:view(Buffer.from(a.buffer)),componentType:integer?5123:type==='VEC4'?5121:5126,count:values.length/size,type};if(type==='VEC4')item.normalized=true;if(integer&&values.some(v=>v>65535))throw Error('Chunk exceeds 16-bit indices');if(type==='VEC3'){item.min=Array.from({length:3},(_,k)=>values.reduce((v,n,i)=>i%3===k?Math.min(v,n):v,Infinity));item.max=Array.from({length:3},(_,k)=>values.reduce((v,n,i)=>i%3===k?Math.max(v,n):v,-Infinity));}out.accessors.push(item);return id;}
for(const [key,b] of buckets){const p={attributes:{POSITION:attr(b.vertices.flatMap(v=>v.slice(0,3)),3),TEXCOORD_0:attr(b.vertices.flatMap(v=>v.slice(6,8)),2,'VEC2'),COLOR_0:attr(b.vertices.flatMap(v=>v.slice(8,12)),4,'VEC4')},indices:attr(b.indices,1,'SCALAR',true),material:b.material,mode:4};out.scenes[0].nodes.push(out.nodes.length);out.nodes.push({mesh:out.meshes.length,name:'subzero:'+key});out.meshes.push({primitives:[p]});}
for(const im of g.images){const v=g.bufferViews[im.bufferView];out.images.push({mimeType:im.mimeType,bufferView:view(bin.subarray(v.byteOffset||0,(v.byteOffset||0)+v.byteLength))});}
out.buffers.push({byteLength:length});const json=Buffer.from(JSON.stringify(out)),jp=Buffer.alloc(Math.ceil(json.length/4)*4,32);json.copy(jp);const header=Buffer.alloc(20);header.writeUInt32LE(0x46546c67,0);header.writeUInt32LE(2,4);header.writeUInt32LE(28+jp.length+length,8);header.writeUInt32LE(jp.length,12);header.writeUInt32LE(0x4e4f534a,16);const bh=Buffer.alloc(8);bh.writeUInt32LE(length,0);bh.writeUInt32LE(0x004e4942,4);const result=Buffer.concat([header,jp,bh,...chunks]);fs.writeFileSync(path.join(dir,'subzero.glb'),result);fs.writeFileSync(path.join(dir,'subzero-collision.bin'),Buffer.from(new Float32Array(collision).buffer));
const report={name:'Subzero',scale,offset,inputTriangles,renderTriangles:inputTriangles-removed,collisionTriangles:collision.length/9,chunks:buckets.size,sourceBytes:source.length,optimizedBytes:result.length,attribution:g.asset.extras};fs.writeFileSync(path.join(dir,'subzero-report.json'),JSON.stringify(report,null,2)+'\n');for(const name of ['subzero.glb','subzero-collision.bin']){const compressed=require('node:zlib').gzipSync(fs.readFileSync(path.join(dir,name)),{level:9});fs.writeFileSync(path.join(dir,name+'.gz'),compressed);report[name+'GzipBytes']=compressed.length;}fs.writeFileSync(path.join(dir,'subzero-report.json'),JSON.stringify(report,null,2)+'\n');console.log(report);
